name: AirborneFieldGuide
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - open_clip_torch
    - DeepForest
    - label_studio
    - comet_ml
    - dask
    - dask-jobqueue